### ISSUE TITLE
Packages missing from README

### ISSUE THREAD

**Issue by PeteHaitch** [dcgerard/mouthwash_sims#1]
Hi David,

A heads up: I'm a reviewer of the MOUTHWASH paper. I thought I'd post a few minor issues I had with re-running the simulations (I'll also touch on these in the formal review, which you should have shortly).

I needed to install the **seqgendiff**, **tidyverse**, and **ashr** packages to run the analysis (via `make`) but these were missing from the installation instructions in the `README` (there may be others that I just happened to already have installed).

Could you please ensure that instructions for installing all required packages are included in the `README`. 

Cheers,
Pete

**Comment by dcgerard** [comment]
Thanks for looking at this carefully.

I added the install instructions for `seqgendiff`, `tidyverse`, and `ashr`. But I'll look more carefully to make sure that there aren't any other unmentioned but needed packages.
