### ISSUE TITLE
Case sensitive `gencode.v19.genes.v6p_model.patched_contigs.gtf`

### ISSUE THREAD

**Issue by PeteHaitch** [dcgerard/mouthwash_sims#2]
I had to rename `gencode.v19.genes.v6p_model.patched_contigs.gtf` to `gencode.v19.genes.V6p_model.patched_contigs.gtf` (lowercase to uppercase `V6p`) to get `make gtex_analysis` to run

**Comment by pcarbo** [comment]
@PeteHaitch @dcgerard Should now be fixed in [my fork](https://github.com/pcarbo/mouthwash_sims).

**Comment by dcgerard** [comment]
Fixed by 2a59116d46559fb71ba81d0153eb646288b16e4d.
