### ISSUE TITLE
Shiny app for h-scHKgenes.csv no longer available

### ISSUE THREAD

**Issue by jdblischak** [dcgerard/mouthwash_sims#5]
I can't access the Shiny app hosted at http://shiny.maths.usyd.edu.au/scHK/. It's also not present in the list of Shiny apps at http://shiny.maths.usyd.edu.au/, so I assume it is no longer supported.

Would it be possible to commit `h-scHKgenes.csv` to the repository? Given that `lin_hk_genes.csv` only has 1125 lines, I assume that  `h-scHKgenes.csv` isn't that big of a file.

**Comment by dcgerard** [comment]
Added! Thanks for noticing this!
